models/TerminoReferencia.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "TerminoReferencia".
 *
 * @property integer $ID
 * @property string $Documento
 * @property integer $Estado
 * @property string $FechaRegistro
 * @property integer $Situacion
 * @property string $CodigoProyecto
 * @property integer $TipoServicio
 * @property double $MontoTotal
 * @property integer $Duracion
 * @property integer $AreSubCategoriaID
 * @property integer $PaDetalleID
 *
 * @property Orden[] $ordens
 */
class TerminoReferencia extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public $archivo;
    public $ComponenteID;
    public $ActividadID;
    //public $AreSubCategoriaID;
    public $TerminoReferenciaID;
    public static function tableName()
    {
        return 'TerminoReferencia';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['Documento', 'CodigoProyecto'], 'string'],
            [['Estado', 'Situacion', 'TipoServicio', 'Duracion', 'AreSubCategoriaID', 'PaDetalleID'], 'integer'],
            [['FechaRegistro','archivo','ComponenteID','ActividadID'], 'safe'],
            [['MontoTotal'], 'number'],
            [['archivo'],'file'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'ID' => 'ID',
            'Documento' => 'Documento',
            'Estado' => 'Estado',
            'FechaRegistro' => 'Fecha Registro',
            'Situacion' => 'Situacion',
            'CodigoProyecto' => 'Codigo Proyecto',
            'TipoServicio' => 'Tipo Servicio',
            'MontoTotal' => 'Monto Total',
            'Duracion' => 'Duracion',
            'AreSubCategoriaID' => 'Are Sub Categoria ID',
            'PaDetalleID' => 'Pa Detalle ID',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOrdens()
    {
        return $this->hasMany(Orden::className(), ['TerminoReferenciaID' => 'ID']);
    }
}

controllers/TerminoReferenciaController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use app\models\PasoCritico;
use app\models\Usuario;
use app\models\Persona;
use app\models\Investigador;
use app\models\Proyecto;
use app\models\InformacionGeneral;
use app\models\Poa;
use app\models\Componente;
use app\models\Actividad;
use app\models\CronogramaProyecto;
use app\models\ActRubroElegible;
use app\models\CronogramaComponente;
use app\models\CronogramaActividad;
use app\models\CronogramaActRubroElegible;
use app\models\RubroElegible;
use app\models\AreSubCategoria;
use app\models\CronogramaAreSubCategoria;
use app\models\MarcoLogicoActividad;
use app\models\AreSubCategoriaObservacion;
use app\models\Requerimiento;
use app\models\TerminoReferencia;
use app\models\Tarea;
use yii\web\UploadedFile;


class TerminoReferenciaController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex($CodigoProyecto=NULL)
    {
        $this->layout='estandar';
        if($CodigoProyecto)
        {
            
        }
        else{
            $usuario=Usuario::findOne(\Yii::$app->user->id);
            $datosInvestigador=Persona::findOne($usuario->PersonaID);
            $investigador=Investigador::find()->where('UsuarioID=:UsuarioID',[':UsuarioID'=>$usuario->id])->one();
            $informacionGeneral=InformacionGeneral::find()->where('InvestigadorID=:InvestigadorID',[':InvestigadorID'=>$investigador->ID])->one();
            $CodigoProyecto=$informacionGeneral->Codigo;
        }
        return $this->render('index',['CodigoProyecto'=>$CodigoProyecto]);
    }
    
    public function actionListaTerminosReferencias($CodigoProyecto=null)
    {
        if($CodigoProyecto)
        {
            
        }
        else{
            $usuario=Usuario::findOne(\Yii::$app->user->id);
            $datosInvestigador=Persona::findOne($usuario->PersonaID);
            $investigador=Investigador::find()->where('UsuarioID=:UsuarioID',[':UsuarioID'=>$usuario->id])->one();
            $informacionGeneral=InformacionGeneral::find()->where('InvestigadorID=:InvestigadorID',[':InvestigadorID'=>$investigador->ID])->one();
            $CodigoProyecto=$informacionGeneral->Codigo;
        }
        
        $resultados = (new \yii\db\Query())
            ->select('TerminoReferencia.ID,TerminoReferencia.TipoServicio,TerminoReferencia.FechaRegistro,TerminoReferencia.Documento,TerminoReferencia.Situacion')
            ->from('InformacionGeneral')
            ->innerJoin('Investigador','InformacionGeneral.InvestigadorID=Investigador.ID')
            ->innerJoin('Usuario','Usuario.ID=Investigador.UsuarioID')
            ->innerJoin('Proyecto','Proyecto.InvestigadorID=Investigador.ID')
            ->innerJoin('TerminoReferencia','TerminoReferencia.CodigoProyecto=InformacionGeneral.Codigo')
            ->where(['InformacionGeneral.Codigo'=>$CodigoProyecto])
            ->distinct()
            ->all();

        $nro=0;
        foreach($resultados as $result)
        {
            $nro++;
            echo "<tr>";
            echo "<td> N° Término " . $result["ID"] . "</td>";
            echo "<td>" . $this->getTipoServicio($result["TipoServicio"]) . "</td>";
            echo "<td>" . $result["FechaRegistro"] . "</td>";
            echo "<td>" . $this->getSituacion($result["Situacion"]) . "</td>";
            echo "<td><a target='_blank' href='terminosreferencias/" . $result["Documento"] . "'><span>descargar</span></a></td>";
            if($result["Situacion"]==0)
            {
                echo "<td><a href='#' class='btn-edit-termino' data-id='".$result["ID"]."'><i class='fa fa-edit fa-lg'></i></a> <a href='#' class='btn-remove' data-id='".$result["ID"]."'><i class='fa fa-remove fa-lg'></i></a></td>";    
            }
            else
            {
                echo "<td></td>";
            }
            
            echo "</tr>";
        }
    }
    
    public function actionCrear($CodigoProyecto)
    {
        $this->layout='vacio';
        $informacionGeneral=InformacionGeneral::find()->where('Codigo=:Codigo',[':Codigo'=>$CodigoProyecto])->one();
        $proyecto=Proyecto::find()->where('InvestigadorID=:InvestigadorID',[':InvestigadorID'=>$informacionGeneral->InvestigadorID])->one();
        $poa=Poa::find()->where('ProyectoID=:ProyectoID',[':ProyectoID'=>$proyecto->ID])->one();
        $componentes=Componente::find()->where('PoaID=:PoaID',[':PoaID'=>$poa->ID])->all();
        $terminoReferencia=new TerminoReferencia;
        if($terminoReferencia->load(Yii::$app->request->post())){
            $Componente=Componente::findOne($terminoReferencia->ComponenteID);
            $Actividad=Actividad::findOne($terminoReferencia->ActividadID);
            $Recurso=AreSubCategoria::findOne($terminoReferencia->AreSubCategoriaID);
            //var_dump($Componente);die;
            $terminoReferencia->CodigoPoa="O.".$Componente->Correlativo." A.".$Actividad->Correlativo." R.".$Recurso->Correlativo;
            
            
            $terminoReferencia->Situacion=0;
            $terminoReferencia->Estado=1;
            $terminoReferencia->FechaRegistro=date('Ymd');
            $terminoReferencia->save();
            
            $terminoReferencia->archivo = UploadedFile::getInstance($terminoReferencia, 'archivo');
            
            if($terminoReferencia->archivo)
            {
                $terminoReferencia->archivo->saveAs('terminosreferencias/' . $terminoReferencia->ID . '.' . $terminoReferencia->archivo->extension);
                $terminoReferencia->Documento=$terminoReferencia->ID . '.' . $terminoReferencia->archivo->extension;
            }
            $terminoReferencia->update();
            return $this->redirect(['/termino-referencia']);
        }
        return $this->render('_form',['CodigoProyecto'=>$CodigoProyecto,'componentes'=>$componentes]);
    }
    
    public function actionActualizar($ID=null)
    {
        $this->layout='vacio';
        $terminoReferencia=TerminoReferencia::find()
                ->select('TerminoReferencia.*,Componente.ID as ComponenteID,Actividad.ID as ActividadID,AreSubCategoria.ID as AreSubCategoriaID')
                ->innerJoin('AreSubCategoria','AreSubCategoria.ID=TerminoReferencia.AreSubCategoriaID')
                ->innerJoin('ActRubroElegible','ActRubroElegible.ID=AreSubCategoria.ActRubroElegibleID')
                ->innerJoin('Actividad','Actividad.ID=ActRubroElegible.ActividadID')
                ->innerJoin('Componente','Componente.ID=Actividad.ComponenteID')
                ->where('TerminoReferencia.ID=:ID',['ID'=>$ID])->one();
                
        $informacionGeneral=InformacionGeneral::find()->where('Codigo=:Codigo',[':Codigo'=>$terminoReferencia->CodigoProyecto])->one();
        $proyecto=Proyecto::find()->where('InvestigadorID=:InvestigadorID',[':InvestigadorID'=>$informacionGeneral->InvestigadorID])->one();
        $poa=Poa::find()->where('ProyectoID=:ProyectoID',[':ProyectoID'=>$proyecto->ID])->one();
        $componentes=Componente::find()->where('PoaID=:PoaID',[':PoaID'=>$poa->ID])->all();
        $actividades=Actividad::find()->select('ID,Nombre,Correlativo')->where('ComponenteID=:ComponenteID',[':ComponenteID'=>$terminoReferencia->ComponenteID])->groupBy('ID,Nombre,Correlativo')->orderBy('Correlativo')->all();
        $recursos=AreSubCategoria::find()->select('AreSubCategoria.ID,AreSubCategoria.Nombre')->innerJoin('ActRubroElegible','ActRubroElegible.ID=AreSubCategoria.ActRubroElegibleID')->where('ActRubroElegible.ActividadID=:ActividadID',[':ActividadID'=>$terminoReferencia->ActividadID])->groupBy('AreSubCategoria.ID,AreSubCategoria.Nombre,AreSubCategoria.Correlativo')->orderBy('AreSubCategoria.Correlativo')->all();
        
        if($terminoReferencia->load(Yii::$app->request->post())){
            $terminoReferencia->save();
            $terminoReferencia->archivo = UploadedFile::getInstance($terminoReferencia, 'archivo');
            if($terminoReferencia->archivo)
            {
                $terminoReferencia->archivo->saveAs('terminosreferencias/' . $terminoReferencia->ID . '.' . $terminoReferencia->archivo->extension);
                $terminoReferencia->Documento=$terminoReferencia->ID . '.' . $terminoReferencia->archivo->extension;
            }
            $terminoReferencia->update();
            return $this->redirect(['/termino-referencia']);
        }
        return $this->render('_form_actualizar',['termino'=>$terminoReferencia,'ID'=>$ID,'componentes'=>$componentes,'actividades'=>$actividades,'recursos'=>$recursos]);
    }
    
    
    public function actionActividades()
    {
        if(isset($_POST['ComponenteID']) && trim($_POST['ComponenteID'])!='')
        {
            $ComponenteID=$_POST['ComponenteID'];

views/termino-referencia/_form.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

?>

<?php $form = ActiveForm::begin(
    [
        'action'            => 'termino-referencia/crear?CodigoProyecto='.$CodigoProyecto,
        'options'           => [
            'enctype'       =>'multipart/form-data',
            'id'            => 'frmTerminoReferencia',
            
        ]
    ]
); ?>
    <input type="hidden" name="TerminoReferencia[CodigoProyecto]" value="<?php echo $CodigoProyecto ?>">
    <div class="modal-body">
        <div class="form-horizontal">
            
            <div class="form-group">
                <label class="col-sm-3 control-label">Tipo de Servicio:<span class="f_req">*</span></label>
                <div class="col-sm-9">
                    <select class="form-control" name="TerminoReferencia[TipoServicio]">
                        <option>[SELECCIONE]</option>
                        <option value=1>Términos de referencias para consultoria</option>
                        <option value=2>Términos de referencias para no consultoria</option>
                        <option value=3>Especificaciones Técnicas</option>
                    </select>
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-3 control-label">Monto Total:<span class="f_req">*</span></label>
                <div class="col-sm-9">
                    <input class="form-control" type="text" name="TerminoReferencia[MontoTotal]" id="terminoreferencia-montototal">
                </div>
            </div>
            <!--
            <div class="form-group">
                <label class="col-sm-3 control-label">Duración:(en días)<span class="f_req">*</span></label>
                <div class="col-sm-9">
                    <input class="form-control" type="text" name="TerminoReferencia[Duracion]" id="terminoreferencia-duracion">
                </div>
            </div>
            -->
            <div class="form-group">
                <label class="col-sm-3 control-label">Objetivo:<span class="f_req">*</span></label>
                <div class="col-sm-9">
                    <select class="form-control" name="TerminoReferencia[ComponenteID]" id="terminoreferencia-componenteid" onchange="Actividad($(this).val())">
                        <option>[SELECCIONE]</option>
                        <?php foreach($componentes as $componente){ ?>
                            <option value="<?= $componente->ID ?>"><?= $componente->Nombre ?></option>
                        <?php } ?>
                    </select>
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-3 control-label">Actividad:<span class="f_req">*</span></label>
                <div class="col-sm-9">
                    <select class="form-control" name="TerminoReferencia[ActividadID]" id="terminoreferencia-actividadid" onchange="Recurso($(this).val())">
                        
                    </select>
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-3 control-label">Recurso:<span class="f_req">*</span></label>
                <div class="col-sm-9">
                    <select class="form-control" name="TerminoReferencia[AreSubCategoriaID]" id="terminoreferencia-areasubcategoriaid">
                    </select>
                </div>
            </div>
            
            <div class="form-group">
                <label class="col-sm-3 control-label">Documento:<span class="f_req">*</span></label>
                <div class="col-sm-9">
                    <input class="form-control" type="file" name="TerminoReferencia[archivo]" id="terminoreferencia-archivo">
                </div>
            </div>
            
        </div>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
        <button type="submit" class="btn btn-primary"><i class="fa fa-check"></i>&nbsp;Guardar</button>
    </div>
<?php ActiveForm::end(); ?>
<?php
    $actividades=Yii::$app->getUrlManager()->createUrl('termino-referencia/actividades');
    $recursos=Yii::$app->getUrlManager()->createUrl('termino-referencia/recursos');
?>
<script>
    var $form = $('#frmRequerimientos');
    var formParsleyRequerimientos = $form.parsley(defaultParsleyForm());
    function Actividad(valor) {
        var ComponenteID=valor;
        var toke = '<?=Yii::$app->request->getCsrfToken()?>';
        $.ajax({
            url: '<?= $actividades ?>',
            type: 'POST',
            async: false,
            data: {ComponenteID:ComponenteID,_csrf: toke},
            success: function(data){
               $( "#terminoreferencia-actividadid" ).html( data );
            }
        });
    }
    
    function Recurso(valor) {
        var ActividadID=valor;
        var toke = '<?=Yii::$app->request->getCsrfToken()?>';
        $.ajax({
            url: '<?= $recursos ?>',
            type: 'POST',
            async: false,
            data: {ActividadID:ActividadID,_csrf: toke},
            success: function(data){
               $( "#terminoreferencia-areasubcategoriaid" ).html( data );
            }
        });
    }
</script>

views/termino-referencia/_form_actualizar.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

?>

<?php $form = ActiveForm::begin(
    [
        'action'            => 'termino-referencia/actualizar?ID='.$ID,
        'options'           => [
            'enctype'       =>'multipart/form-data',
            'id'            => 'frmTerminoReferencia',
            
        ]
    ]
); ?>
    <div class="modal-body">
        <div class="form-horizontal">
            
            <div class="form-group">
                <label class="col-sm-3 control-label">Tipo de Servicio:<span class="f_req">*</span></label>
                <div class="col-sm-9">
                    <select class="form-control" name="TerminoReferencia[TipoServicio]">
                        <option>[SELECCIONE]</option>
                        <option value=1 <?= ($termino->TipoServicio==1)?'selected':'';?>>Términos de referencias para consultoria</option>
                        <option value=2 <?= ($termino->TipoServicio==2)?'selected':'';?>>Términos de referencias para no consultoria</option>
                        <option value=3 <?= ($termino->TipoServicio==3)?'selected':'';?>>Especificaciones Técnicas</option>
                    </select>
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-3 control-label">Monto Total:<span class="f_req">*</span></label>
                <div class="col-sm-9">
                    <input class="form-control" type="text" name="TerminoReferencia[MontoTotal]" id="terminoreferencia-montototal" value="<?= $termino->MontoTotal; ?>">
                </div>
            </div>
            <!--
            <div class="form-group">
                <label class="col-sm-3 control-label">Duración:(en días)<span class="f_req">*</span></label>
                <div class="col-sm-9">
                    <input class="form-control" type="text" name="TerminoReferencia[Duracion]" id="terminoreferencia-duracion" value="<?= $termino->Duracion; ?>">
                </div>
            </div>
            -->
            <div class="form-group">
                <label class="col-sm-3 control-label">Objetivo:<span class="f_req">*</span></label>
                <div class="col-sm-9">
                    <select class="form-control" name="TerminoReferencia[ComponenteID]" id="terminoreferencia-componenteid" onchange="Actividad($(this).val())">
                        <option>[SELECCIONE]</option>
                        <?php foreach($componentes as $componente){ ?>
                            <option value="<?= $componente->ID ?>" <?= ($componente->ID==$termino->ComponenteID)?'selected':'';?>><?= $componente->Nombre ?></option>
                        <?php } ?>
                    </select>
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-3 control-label">Actividad:<span class="f_req">*</span></label>
                <div class="col-sm-9">
                    <select class="form-control" name="TerminoReferencia[ActividadID]" id="terminoreferencia-actividadid" onchange="Recurso($(this).val())">
                        <?php foreach($actividades as $actividad){ ?>
                            <option value="<?= $actividad->ID ?>" <?= ($actividad->ID==$termino->ActividadID)?'selected':'';?>><?= $actividad->Nombre ?></option>
                        <?php } ?>
                    </select>
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-3 control-label">Recurso:<span class="f_req">*</span></label>
                <div class="col-sm-9">
                    <select class="form-control" name="TerminoReferencia[AreSubCategoriaID]" id="terminoreferencia-areasubcategoriaid">
                        <?php foreach($recursos as $recurso){ ?>
                            <option value="<?= $recurso->ID ?>" <?= ($recurso->ID==$termino->AreSubCategoriaID)?'selected':'';?>><?= $recurso->Nombre ?></option>
                        <?php } ?>
                    </select>
                </div>
            </div>
            
            <div class="form-group">
                <label class="col-sm-3 control-label">Documento:<span class="f_req">*</span></label>
                <div class="col-sm-9">
                    <input class="form-control" type="file" name="TerminoReferencia[archivo]" id="terminoreferencia-archivo">
                </div>
            </div>
            
        </div>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
        <button type="submit" class="btn btn-primary"><i class="fa fa-check"></i>&nbsp;Guardar</button>
    </div>
<?php ActiveForm::end(); ?>
<?php
    $actividades=Yii::$app->getUrlManager()->createUrl('requerimiento/actividades');
    $recursos=Yii::$app->getUrlManager()->createUrl('requerimiento/recursos');
?>
<script>
    var $form = $('#frmRequerimientos');
    var formParsleyRequerimientos = $form.parsley(defaultParsleyForm());
    function Actividad(valor) {
        var ComponenteID=valor;
        var toke = '<?=Yii::$app->request->getCsrfToken()?>';
        $.ajax({
            url: '<?= $actividades ?>',
            type: 'POST',
            async: false,
            data: {ComponenteID:ComponenteID,_csrf: toke},
            success: function(data){
               $( "#terminoreferencia-actividadid" ).html( data );
            }
        });
    }
    
    function Recurso(valor) {
        var ActividadID=valor;
        var toke = '<?=Yii::$app->request->getCsrfToken()?>';
        $.ajax({
            url: '<?= $recursos ?>',
            type: 'POST',
            async: false,
            data: {ActividadID:ActividadID,_csrf: toke},
            success: function(data){
               $( "#terminoreferencia-areasubcategoriaid" ).html( data );
            }
        });
    }
</script>

views/termino-referencia/index.php
<link href="https://cdn.datatables.net/1.10.13/css/jquery.dataTables.min.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/jquery.loadingoverlay/latest/loadingoverlay.min.js"></script>
<script src="https://cdn.jsdelivr.net/jquery.loadingoverlay/latest/loadingoverlay_progress.min.js"></script>
<script src=" //cdn.datatables.net/1.10.13/js/jquery.dataTables.min.js"></script>


<div id="page-content" style="min-height: 1342px;">
    
    <div id="wrap">
        <div id="page-heading">
            <h1>Términos de referencia</h1>
        </div>
        
           
        <div class="container">
             <div class="form-group">
                <button class="btn btn-crear-termino" data-codigo-proyecto="<?= $CodigoProyecto ?>">Generar Término de Referencia</button>
                <a class="btn " href="documentos/1_MODELO_ESPECIFICACIONES_TECNICAS.docx">Plantilla de especificaciones técnicas</a>
                <a class="btn " href="documentos/1_MODELO_TR_CONSULTORIA.docx">Plantilla de T.R. Consultoria</a>
                <a class="btn " href="documentos/1_MODELO_TR_SERVICIOS_NO_CONSULTORIA.docx">Plantilla de T.R. No Consultoria</a>
            </div>
            <div class="table-responsive">
                <table id="proyectos" class="display table table-bordered table-striped table-condensed table-hover" cellspacing="0" >
                    <thead>
                        <tr>
                            <th>N° Término</th>
                            <th>Tipo de Servicio</th>
                            <th>Fecha Registro</th>
                            <th>Situación</th>
                            <th>Descargar</th>
                            <th>Acciones</th>
                        </tr>
                    </thead>
                    <tbody></tbody>
                </table>
            </div>
        </div>
    </div>
</div>


<div class="modal fade" id="modal-ctrl-termino" tabindex="-1" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
                <h4 class="modal-title">Términos de referencia</h4>
            </div>
            <div class="modal-body-main">
            </div>
        </div>
    </div>
</div>

<script>
    function js_buscar()
    {
       
    }
    var tblresultjs;
        var configDTjs={
            "order": [[ 2, "desc" ]],
                "language": {
                    "sProcessing":    "Procesando...",
                    "sLengthMenu":    "Mostrar _MENU_ registros",
                    "sZeroRecords":   "No se encontraron resultados",
                    "sEmptyTable":    "Ningún dato disponible en esta lista",
                    "sInfo":          "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
                    "sInfoEmpty":     "Mostrando registros del 0 al 0 de un total de 0 registros",
                    "sInfoFiltered":  "(filtrado de un total de _MAX_ registros)",
                    "sInfoPostFix":   "",
                    "sSearch":        "Buscar:",
                    "sUrl":           "",
                    "sInfoThousands":  ",",
                    "sLoadingRecords": "Cargando...",
                    "oPaginate": {
                        "sFirst":    "Primero",
                        "sLast":    "Último",
                        "sNext":    "Siguiente",
                        "sPrevious": "Anterior"
                    },
                    "oAria": {
                        "sSortAscending":  ": Activar para ordenar la columna de manera ascendente",
                        "sSortDescending": ": Activar para ordenar la columna de manera descendente"
                    }
                }
        };
    $(document).ready(function() {
        var CodigoProyecto="<?= $CodigoProyecto ?>";
        $.ajax({
            url:'termino-referencia/lista-terminos-referencias?CodigoProyecto='+CodigoProyecto,
            async:false,
            data:{},
            beforeSend:function()
            {
                $('.panel-default').LoadingOverlay("show");
            },
            success:function(result)
            {
                    //$tblresultjs.destroy();//
                    $("#proyectos tbody").html(result);
                    $('#proyectos').DataTable(configDTjs);
                    //tblresultjs=$('#example').DataTable(configDTjs);
                    $('.panel-default').LoadingOverlay("hide",true);
            },
            error:function(){
                $('.panel-default').LoadingOverlay("hide",true);
                alert('Error al realizar el proceso de busqueda.');
            }
        });
        
    } );
    
    $('body').on('click', '.btn-crear-termino', function (e) {
        e.preventDefault();
        var CodigoProyecto = $(this).attr('data-codigo-proyecto');
        $('#modal-ctrl-termino .modal-body-main').load('<?= \Yii::$app->request->BaseUrl ?>/termino-referencia/crear?CodigoProyecto='+CodigoProyecto);
        $('#modal-ctrl-termino').modal('show');
    });
    
    /*
    $('body').on('click', '#btn-guardar-requerimientos', function (e) {
        
        e.preventDefault();
        // alert('s');
        
        var $btn = $(this);
        $btn.attr('disabled', 'disabled');
        var isValid = formParsleyRequerimientos.validate();
        if (isValid) {
            sendFormNoMessage($('#frmRequerimientos'), $(this), function (msg) {
                
                $("#modal-ctrl-requerimiento").modal('hide');
                _pageLoadingEnd();
		
            });
        } else {
        }
    });
    */
    $('body').on('click', '.btn-edit-termino', function (e) {
        e.preventDefault();
        var id=$(this).attr('data-id');
        $('#modal-ctrl-termino .modal-body-main').load('<?= \Yii::$app->request->BaseUrl ?>/termino-referencia/actualizar?ID='+id);
        $('#modal-ctrl-termino').modal('show');
    });
    
    $('body').on('click', '.btn-remove', function (e) {
        e.preventDefault();
        var $this = $(this);
        bootboxConfirmEliminar($this,
        'Está seguro de eliminar el término de referencia?',
        function () {
            var id = $this.attr('data-id');
            var toke = '<?=Yii::$app->request->getCsrfToken()?>';
            $.get('<?= \Yii::$app->request->BaseUrl ?>/termino-referencia/eliminar', { id: id ,_csrf: toke }, function (data) {
                var jx = JSON.parse(data);
                if (jx.Success == true) {
                    
                }
            });
        });
    });
</script>