models/UsuarioProyecto.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "UsuarioProyecto".
 *
 * @property integer $ID
 * @property integer $UsuarioID
 * @property string $CodigoProyecto
 * @property integer $Estado
 * @property string $FechaRegistro
 */
class UsuarioProyecto extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'UsuarioProyecto';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            //[['ID'], 'required'],
            [['ID', 'UsuarioID', 'Estado'], 'integer'],
            [['CodigoProyecto'], 'string'],
            [['FechaRegistro'], 'safe'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'ID' => 'ID',
            'UsuarioID' => 'Usuario ID',
            'CodigoProyecto' => 'Codigo Proyecto',
            'Estado' => 'Estado',
            'FechaRegistro' => 'Fecha Registro',
        ];
    }
}

controllers/UsuarioProyectoController.php
<?php

namespace app\controllers;

use Yii;
use app\models\UsuarioProyecto;
use app\models\UsuarioProyectoSearch;
use app\models\Usuario;
use app\models\InformacionGeneral;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * UsuarioProyectoController implements the CRUD actions for UsuarioProyecto model.
 */
class UsuarioProyectoController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all UsuarioProyecto models.
     * @return mixed
     */
    public function actionIndex()
    {
        $this->layout='estandar';
        $searchModel = new UsuarioProyectoSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single UsuarioProyecto model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new UsuarioProyecto model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $this->layout='estandar';
        $model = new UsuarioProyecto();
        $usuarios=Usuario::find()
                ->select('Usuario.ID,Usuario.username')
                ->innerJoin('UsuarioRol','UsuarioRol.UsuarioID=Usuario.ID')
                ->where('RolID in (2,10)')
                ->all();
        $codigos=InformacionGeneral::find()->all();
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->ID]);
        } else {
            return $this->render('create', [
                'model' => $model,
                'usuarios'=> $usuarios,
                'codigos'=> $codigos
            ]);
        }
    }
    
    public function actionCrear()
    {
        $this->layout='vacio';
        $model = new UsuarioProyecto();
        $usuarios=Usuario::find()
                ->select('Usuario.ID,Usuario.username')
                ->innerJoin('UsuarioRol','UsuarioRol.UsuarioID=Usuario.ID')
                ->all();
        $codigos=InformacionGeneral::find()->all();
        if ($model->load(Yii::$app->request->post())) {
            $model->save();
            return $this->redirect(['/usuario-proyecto']);
        }
        
        return $this->render('crear', [
            'model' => $model,
            'usuarios'=> $usuarios,
            'codigos'=> $codigos
        ]);
    }

    /**
     * Updates an existing UsuarioProyecto model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $this->layout='estandar';
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->ID]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing UsuarioProyecto model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the UsuarioProyecto model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return UsuarioProyecto the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = UsuarioProyecto::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
    
    public function actionLista()
    {
        
        $asignados = (new \yii\db\Query())
            ->select('Persona.ApellidoPaterno,Persona.ApellidoMaterno,Persona.Nombre,InformacionGeneral.Codigo')
            ->from('UsuarioProyecto')
            ->innerJoin('Usuario','Usuario.ID=UsuarioProyecto.UsuarioID')
            ->innerJoin('Persona','Usuario.PersonaID=Persona.ID')
            ->innerJoin('InformacionGeneral','InformacionGeneral.Codigo=UsuarioProyecto.CodigoProyecto')
            //->innerJoin('Proyecto','Proyecto.ID = UsuarioProyecto.ProyectoID')
            //->where(['UsuarioRol.RolID'=>2])
            ->distinct()
            ->all();
        $nro=0;
        foreach($asignados as $asignado)
        {
            $nro++;

            echo "<tr>";
                echo "<td>" . $asignado["Nombre"] . "". $asignado["ApellidoPaterno"] ."". $asignado["ApellidoMaterno"] ."</td>";
                echo "<td> Proyecto " . $asignado["Codigo"] . "</td>";
                echo "<td></td>";
            echo "</tr>";
        }
    }
}

views/usuario-proyecto/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\UsuarioProyecto */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="usuario-proyecto-form">

    <?php $form = ActiveForm::begin(); ?>
    <div class="form-group field-usuarioproyecto-usuarioid">
        <label class="control-label" for="usuarioproyecto-usuarioid">Usuario ID</label>
        <select id="usuarioproyecto-usuarioid" class="form-control" name="UsuarioProyecto[UsuarioID]">
            <option value>Seleccionar</option>
            <?php foreach($usuarios as $usuario){ ?>
                <option value="<?= $usuario->ID ?>"><?= $usuario->username ?></option>
            <?php } ?>
        </select>
    </div>
    <div class="form-group field-usuarioproyecto-codigoproyecto">
        <label class="control-label" for="usuarioproyecto-codigoproyecto">Codigo Proyecto</label>
        <select id="usuarioproyecto-codigoproyecto" class="form-control" name="UsuarioProyecto[CodigoProyecto]">
            <option value>Seleccionar</option>
            <?php foreach($codigos as $codigo){ ?>
                <option value="<?= $codigo->Codigo ?>"><?= $codigo->Codigo ?></option>
            <?php } ?>
        </select>
    </div>
   
    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/usuario-proyecto/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\UsuarioProyectoSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="usuario-proyecto-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'ID') ?>

    <?= $form->field($model, 'UsuarioID') ?>

    <?= $form->field($model, 'CodigoProyecto') ?>

    <?= $form->field($model, 'Estado') ?>

    <?= $form->field($model, 'FechaRegistro') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/usuario-proyecto/crear.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
?>
<?php $form = ActiveForm::begin(
    [
        'action'            => \Yii::$app->request->BaseUrl.'/usuario-proyecto/crear',
        'options'           => [
            'enctype'       =>'multipart/form-data',
            'id'            => 'frmAdjuntar',
        ]
    ]
); ?>
<div class="modal-body">
    <div class="form-horizontal">
        <div class="form-group field-usuarioproyecto-usuarioid">
            <label class="control-label" for="usuarioproyecto-usuarioid">Usuario ID</label>
            <select id="usuarioproyecto-usuarioid" class="form-control" name="UsuarioProyecto[UsuarioID]">
                <option value>Seleccionar</option>
                <?php foreach($usuarios as $usuario){ ?>
                    <option value="<?= $usuario->ID ?>"><?= $usuario->username ?></option>
                <?php } ?>
            </select>
        </div>
        <div class="form-group field-usuarioproyecto-codigoproyecto">
            <label class="control-label" for="usuarioproyecto-codigoproyecto">Codigo Proyecto</label>
            <select id="usuarioproyecto-codigoproyecto" class="form-control" name="UsuarioProyecto[CodigoProyecto]">
                <option value>Seleccionar</option>
                <?php foreach($codigos as $codigo){ ?>
                    <option value="<?= $codigo->Codigo ?>"><?= $codigo->Codigo ?></option>
                <?php } ?>
            </select>
        </div>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
        <button id="btn-save-adjuntar" type="submit" class="btn btn-primary">Guardar</button>
        
    </div>
</div>
<?php ActiveForm::end(); ?>

<script>
    var formParsleyAdjuntar = $('#frmAdjuntar').parsley(defaultParsleyForm());
    /*$('#btn-save-adjuntar').click(function (e) {
        e.preventDefault();
        var isValid = formParsleyAdjuntar.validate();
        if (isValid) {
            sendForm($('#frmAdjuntar'), $(this), function (eve) {
                console.log(eve);
            });
        }
    });*/
</script>

views/usuario-proyecto/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\UsuarioProyecto */

?>
<div id="page-content" style="min-height: 754px;">
    <div id="wrap">
        <div id="page-heading">
            <h1>Asignar proyecto </h1>
        </div>
        <div class="container">
            <div class="usuario-proyecto-create">
            
                <h1><?= Html::encode($this->title) ?></h1>
            
                <?= $this->render('_form', [
                    'model' => $model,
                    'usuarios'=> $usuarios,
                    'codigos'=> $codigos
                ]) ?>
            
            </div>
        </div>
    </div>
</div>

views/usuario-proyecto/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\UsuarioProyectoSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

?>
<link href="https://cdn.datatables.net/1.10.13/css/jquery.dataTables.min.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/jquery.loadingoverlay/latest/loadingoverlay.min.js"></script>
<script src="https://cdn.jsdelivr.net/jquery.loadingoverlay/latest/loadingoverlay_progress.min.js"></script>
<script src=" //cdn.datatables.net/1.10.13/js/jquery.dataTables.min.js"></script>
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">

<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<div id="page-content" style="min-height: 1342px;">
    <div id="wrap">
        <div id="page-heading">
            <h1>Asignar usuarios</h1>
        </div>
        <div class="container">
             <div class="form-group">
                <button class="btn btn-crear-asignar-usuario">Generar asignación</button>
                <!--<a class="btn " href="documentos/0_OFICIO_MODELO_REQUERIMIENTO.docx">Descargar plantilla</a>-->
            </div>
            <div class="table-responsive">
                <table id="usuarios-proyectos" class="display table table-bordered table-striped table-condensed table-hover" cellspacing="0" >
                    <thead>
                        <tr>
                            <th>Nombres y Apellidos</th>
                            <th>Código de Proyecto</th>
                            <th>Acciones</th>
                        </tr>
                    </thead>
                    <tbody></tbody>
                </table>
            </div>
            <a class="btn" href="<?= Yii::$app->getUrlManager()->createUrl('usuario-proyecto/excel') ?>">Descargar Excel</a>
        </div>
    </div>
</div>
<div class="modal fade" id="modal-ctrl-usuario-asignar" tabindex="-1" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
                <h4 class="modal-title">Asignar Proyecto</h4>
            </div>
            <div class="modal-body-main">
            </div>
        </div>
    </div>
</div>




<script>
    var tblresultjs;
    var configDTjs={
        "order": [[ 2, "desc" ]],
            "language": {
                "sProcessing":    "Procesando...",
                "sLengthMenu":    "Mostrar _MENU_ registros",
                "sZeroRecords":   "No se encontraron resultados",
                "sEmptyTable":    "Ningún dato disponible en esta lista",
                "sInfo":          "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
                "sInfoEmpty":     "Mostrando registros del 0 al 0 de un total de 0 registros",
                "sInfoFiltered":  "(filtrado de un total de _MAX_ registros)",
                "sInfoPostFix":   "",
                "sSearch":        "Buscar:",
                "sUrl":           "",
                "sInfoThousands":  ",",
                "sLoadingRecords": "Cargando...",
                "oPaginate": {
                    "sFirst":    "Primero",
                    "sLast":    "Último",
                    "sNext":    "Siguiente",
                    "sPrevious": "Anterior"
                },
                "oAria": {
                    "sSortAscending":  ": Activar para ordenar la columna de manera ascendente",
                    "sSortDescending": ": Activar para ordenar la columna de manera descendente"
                }
            }
    };
    $(document).ready(function() {
        $.ajax({
            url:'usuario-proyecto/lista',
            async:false,
            data:{},
            beforeSend:function()
            {
                $('.panel-default').LoadingOverlay("show");
            },
            success:function(result)
            {
                    //$tblresultjs.destroy();//
                    $("#usuarios-proyectos tbody").html(result);
                    $('#usuarios-proyectos').DataTable(configDTjs);
                    //tblresultjs=$('#example').DataTable(configDTjs);
                    $('.panel-default').LoadingOverlay("hide",true);
            },
            error:function(){
                $('.panel-default').LoadingOverlay("hide",true);
                alert('Error al realizar el proceso de busqueda.');
            }
        });
    } );
    
    $('body').on('click', '.btn-crear-asignar-usuario', function (e) {
        e.preventDefault();
        var CodigoProyecto = $(this).attr('data-codigo-proyecto');
        $('#modal-ctrl-usuario-asignar .modal-body-main').load('<?= \Yii::$app->request->BaseUrl ?>/usuario-proyecto/crear');
        $('#modal-ctrl-usuario-asignar').modal('show');
    });
</script>

views/usuario-proyecto/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\UsuarioProyecto */

$this->title = 'Update Usuario Proyecto: ' . $model->ID;
$this->params['breadcrumbs'][] = ['label' => 'Usuario Proyectos', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->ID, 'url' => ['view', 'id' => $model->ID]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="usuario-proyecto-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/usuario-proyecto/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\UsuarioProyecto */

$this->title = $model->ID;
$this->params['breadcrumbs'][] = ['label' => 'Usuario Proyectos', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="usuario-proyecto-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->ID], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->ID], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'ID',
            'UsuarioID',
            'CodigoProyecto',
            'Estado',
            'FechaRegistro',
        ],
    ]) ?>

</div>